language: node_js

node_js:
  - node
  - 8.0.0
  - 9.0.0
  - 10.0.0
  
sudo: false

#before_script:
#- npm install -g minify
#- minify src/beamzer-client.js > dist/beamzer-client.min.js

install:
  - npm install
  
cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm

notifications:
  email: 
    - isocroft@gmail.com